version: 0.1.{build}
skip_tags: true
configuration: Release
platform: AnyCPU
clone_depth: 2
test: off
branches:
  only:
  - master
install:
- choco install gitlink -y
before_build:
- ps: .\SetVersion.ps1
- appveyor-retry dotnet restore -v Minimal
- ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }
before_package:
- ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { GitLink .\ }
#after_test: 
#- ps: .\CreateCoverage.ps1
environment:
  COVERALLS_REPO_TOKEN:
    secure: QZGlO26FXPxhzbeFtexDdxQXlLl5rNH2OCKb3prwdWiAluEWHa7R3NxmwGxn0G7Y
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
build_script:
- dotnet build Dapplo.Bitbucket -c %CONFIGURATION% --no-dependencies
- dotnet build Dapplo.Bitbucket.Tests -c %CONFIGURATION% --no-dependencies
after_build:
- dotnet pack Dapplo.Bitbucket -c %CONFIGURATION% --no-build -o artifacts
#- dotnet pack Dapplo.Bitbucket.PowerShell -c %CONFIGURATION% --no-build -o artifacts
#cache:
#- '%USERPROFILE%\.nuget\packages'
artifacts:
- path: artifacts\**\*.*
  name: NuGet package
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: Fu7vXeOuWmvDK7WGNsEbTIV2vhDV4P6PiK5k1+UZOmwldhCfvUvkA4HOkml+ZE/n
  on:
    branch: master
    is_not_pr: true
    appveyor_repo_commit_message_extended: /\[release\]/
